/**
 * Project Scaffolder — creates baseline Node/TypeScript project structures in
 * empty directories so the compilation sandbox can validate generated code
 * without ENOENT crashes on a blank canvas.
 *
 * Strategy:
 *  1. mkdirSync all required source folders
 *  2. Write package.json + tsconfig.json + src/global.d.ts (wildcard module shim)
 *  3. Write minimal placeholder entry points that compile cleanly
 *  4. Run `npm install --save-dev typescript @types/node` (fast — ~10 s)
 *     so `npm run build` (→ tsc --noEmit) works without the full dependency tree
 */

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { engineerLog } from './logging.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ScaffoldResult {
  backendWasBlank: boolean;
  frontendWasBlank: boolean;
  /** True when at least one project was freshly scaffolded. */
  isBlankCanvas: boolean;
  backendRoot: string;
  frontendRoot: string;
  backendUrl: string;
  frontendUrl: string;
}

// ─── tsconfig templates ───────────────────────────────────────────────────────

const BACKEND_TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2020',
      lib: ['ES2020'],
      module: 'commonjs',
      moduleResolution: 'node',
      outDir: 'dist',
      rootDir: 'src',
      strict: false,
      esModuleInterop: true,
      skipLibCheck: true,
      allowSyntheticDefaultImports: true,
      noImplicitAny: false,
      resolveJsonModule: true,
      noEmit: true,
    },
    include: ['src/**/*.ts'],
    exclude: ['node_modules', 'dist'],
  },
  null,
  2,
);

const FRONTEND_TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2020',
      lib: ['ES2020', 'DOM', 'DOM.Iterable'],
      module: 'commonjs',
      moduleResolution: 'node',
      jsx: 'react-jsx',
      strict: false,
      esModuleInterop: true,
      skipLibCheck: true,
      allowSyntheticDefaultImports: true,
      noImplicitAny: false,
      resolveJsonModule: true,
      noEmit: true,
    },
    include: ['src/**/*.ts', 'src/**/*.tsx'],
    exclude: ['node_modules'],
  },
  null,
  2,
);

// Allow any import without installed @types packages.
// This lets tsc --noEmit pass on scaffolded code that references express,
// mongoose, react, etc. before those packages are npm-installed.
const GLOBAL_DTS = `// Wildcard module shim — allows imports of any package before npm install
// Auto-generated by QA Agent Feature Engineer scaffolder. Do not remove.
declare module '*';
`;

// ─── Per-project scaffolders ──────────────────────────────────────────────────

function scaffoldBackend(root: string, port: number): boolean {
  if (existsSync(path.join(root, 'package.json'))) return false;

  engineerLog(`[SCAFFOLD] Blank backend detected — creating structure at ${root}`);

  const dirs = [
    'src/config',
    'src/controllers',
    'src/middleware',
    'src/models',
    'src/routes',
    'src/services',
  ];
  for (const d of dirs) {
    mkdirSync(path.join(root, d), { recursive: true });
  }

  writeFileSync(
    path.join(root, 'package.json'),
    JSON.stringify(
      {
        name: path.basename(root),
        version: '1.0.0',
        description: 'Backend — scaffolded by QA Agent Feature Engineer',
        main: 'dist/index.js',
        scripts: {
          // tsc --noEmit validates generated TS without needing outDir populated
          build: 'tsc --noEmit',
          dev: 'ts-node-dev --respawn src/index.ts',
          start: 'node dist/index.js',
        },
        dependencies: {},
        devDependencies: {
          typescript: '^5.3.0',
          '@types/node': '^20.0.0',
        },
      },
      null,
      2,
    ),
  );

  writeFileSync(path.join(root, 'tsconfig.json'), BACKEND_TSCONFIG);
  writeFileSync(path.join(root, 'src', 'global.d.ts'), GLOBAL_DTS);

  // Placeholder entry point — OpenRouter replaces this with real code
  writeFileSync(
    path.join(root, 'src', 'index.ts'),
    `// Entry point — QA Agent will replace this with generated application code\nimport express from 'express';\nconst app = express();\napp.use(express.json());\napp.listen(${port}, () => console.log(\`Server on http://localhost:${port}\`));\nexport default app;\n`,
  );

  writeFileSync(
    path.join(root, 'src', 'routes', 'index.ts'),
    `// Routes index — QA Agent will inject generated routes here\nimport { Router } from 'express';\nconst router = Router();\nexport default router;\n`,
  );

  writeFileSync(
    path.join(root, 'src', 'middleware', 'errorHandler.ts'),
    `import type { Request, Response, NextFunction } from 'express';\nexport function errorHandler(err: Error, _req: Request, res: Response, _next: NextFunction) {\n  res.status(500).json({ success: false, message: err.message });\n}\n`,
  );

  writeFileSync(
    path.join(root, 'src', 'config', 'database.ts'),
    `// Database config — QA Agent will populate this\nexport {};\n`,
  );

  engineerLog(`[SCAFFOLD] Backend directories + baseline files created`);
  return true;
}

function scaffoldFrontend(root: string): boolean {
  if (existsSync(path.join(root, 'package.json'))) return false;

  engineerLog(`[SCAFFOLD] Blank frontend detected — creating structure at ${root}`);

  const dirs = [
    'src/app',
    'src/components',
    'src/lib',
    'src/hooks',
    'src/types',
    'public',
  ];
  for (const d of dirs) {
    mkdirSync(path.join(root, d), { recursive: true });
  }

  writeFileSync(
    path.join(root, 'package.json'),
    JSON.stringify(
      {
        name: path.basename(root),
        version: '0.0.0',
        description: 'Frontend — scaffolded by QA Agent Feature Engineer',
        private: true,
        scripts: {
          build: 'tsc --noEmit',
          dev: 'next dev',
          start: 'next start',
          lint: 'next lint',
        },
        dependencies: {},
        devDependencies: {
          typescript: '^5.3.0',
          '@types/node': '^20.0.0',
          '@types/react': '^18.2.0',
          '@types/react-dom': '^18.2.0',
        },
      },
      null,
      2,
    ),
  );

  writeFileSync(path.join(root, 'tsconfig.json'), FRONTEND_TSCONFIG);
  writeFileSync(path.join(root, 'src', 'global.d.ts'), GLOBAL_DTS);

  // Minimal app shell — OpenRouter replaces with real pages
  writeFileSync(
    path.join(root, 'src', 'app', 'layout.tsx'),
    `// Root layout — QA Agent will replace this\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return <html lang="en"><body>{children}</body></html>;\n}\n`,
  );

  writeFileSync(
    path.join(root, 'src', 'app', 'page.tsx'),
    `// Home page — QA Agent will replace this\nexport default function Home() {\n  return <main><h1>Loading…</h1></main>;\n}\n`,
  );

  writeFileSync(
    path.join(root, 'src', 'lib', 'api.ts'),
    `// API helpers — QA Agent will populate this\nexport const BASE_URL = process.env['NEXT_PUBLIC_API_URL'] ?? 'http://localhost:3001';\n`,
  );

  engineerLog(`[SCAFFOLD] Frontend directories + baseline files created`);
  return true;
}

// ─── TypeScript bootstrap ─────────────────────────────────────────────────────

/**
 * Installs the minimum devDependencies needed for `tsc --noEmit` to run.
 * Only installs typescript + @types/node — runtime deps are left for OpenRouter
 * to declare in its generated package.json once it knows the full stack.
 */
function installTypescriptBootstrap(root: string, label: string): void {
  const nodeModules = path.join(root, 'node_modules');
  if (existsSync(nodeModules)) {
    engineerLog(`[SCAFFOLD] ${label} node_modules exists — skipping bootstrap install`);
    return;
  }

  engineerLog(`[SCAFFOLD] ${label} — bootstrapping TypeScript toolchain…`);
  try {
    execSync(
      'npm install --save-dev typescript @types/node @types/react @types/react-dom --no-audit --no-fund --prefer-offline --loglevel=error',
      {
        cwd: root,
        encoding: 'utf-8',
        timeout: 180_000,
        stdio: ['pipe', 'pipe', 'pipe'],
        env: { ...process.env, CI: '1' },
      },
    );
    engineerLog(`[SCAFFOLD] ${label} TypeScript bootstrap complete`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    engineerLog(`[SCAFFOLD] ${label} bootstrap warning (continuing): ${msg.slice(0, 200)}`);
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

export const DEFAULT_BACKEND_URL = 'http://localhost:3001';
export const DEFAULT_FRONTEND_URL = 'http://localhost:5173';
const DEFAULT_BACKEND_PORT = 3001;

/**
 * Checks whether the backend and frontend project roots exist and are
 * initialized. Creates them from scratch when they are absent.
 *
 * Uses mkdirSync for guaranteed synchronous directory creation before any
 * async compiler or OpenRouter operations begin.
 *
 * @param backendRoot Absolute path to the backend project root
 * @param frontendRoot Absolute path to the frontend project root
 */
export function scaffoldWorkspaceIfBlank(
  backendRoot: string,
  frontendRoot: string,
): ScaffoldResult {
  const backendWasBlank = scaffoldBackend(backendRoot, DEFAULT_BACKEND_PORT);
  const frontendWasBlank = scaffoldFrontend(frontendRoot);

  if (backendWasBlank) {
    installTypescriptBootstrap(backendRoot, 'backend');
  }
  if (frontendWasBlank) {
    installTypescriptBootstrap(frontendRoot, 'frontend');
  }

  if (!backendWasBlank && !frontendWasBlank) {
    engineerLog('[SCAFFOLD] Both projects already initialized — no scaffold needed');
  }

  return {
    backendWasBlank,
    frontendWasBlank,
    isBlankCanvas: backendWasBlank || frontendWasBlank,
    backendRoot,
    frontendRoot,
    backendUrl: DEFAULT_BACKEND_URL,
    frontendUrl: DEFAULT_FRONTEND_URL,
  };
}
