/**
 * External Project Sandbox
 *
 * Enforces strict workspace separation between the QA agent's own source
 * tree and the applications it generates. All generated backends, frontends,
 * and project memory banks live in a sibling directory OUTSIDE the agent root.
 *
 * Resolution order for the project root:
 *  1. options.projectRoot  — absolute path supplied by the user
 *  2. Sibling derived from featureSpec slug
 *     e.g. agentRoot=D:\sqa + spec="Build car rental app" → D:\car-rental-app
 *
 * The sandbox root is NEVER allowed to be nested inside the agent root.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { engineerLog } from './logging.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface SandboxConfig {
  /** Absolute path to the external project root (always outside agentRoot) */
  projectRoot: string;
  /** <projectRoot>/backend */
  backendRoot: string;
  /** <projectRoot>/frontend */
  frontendRoot: string;
  /** <projectRoot>/memory-bank */
  memoryBankRoot: string;
  /** <projectRoot>/.env */
  envFilePath: string;
  /** URL-safe slug derived from featureSpec or user-supplied name */
  projectSlug: string;
  /** true when projectRoot did not exist before this call */
  isNew: boolean;
}

// ─── Slug helper ──────────────────────────────────────────────────────────────

export function slugify(text: string): string {
  return (
    text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40) || 'project'
  );
}

// ─── Core resolver ────────────────────────────────────────────────────────────

/**
 * Resolve the external sandbox configuration.
 * Validates the path is not nested inside the agent root.
 * Never creates any directories — call `bootstrapSandboxDirs` for that.
 */
export function resolveSandbox(
  agentRoot: string,
  options: { projectRoot?: string; featureSpec?: string },
): SandboxConfig {
  const slug = slugify(options.featureSpec ?? 'project');
  const parentDir = path.dirname(path.resolve(agentRoot));

  let projectRoot = options.projectRoot
    ? path.resolve(options.projectRoot)
    : path.join(parentDir, slug);

  // Guard: never nest generated projects inside the agent directory
  const normAgent = path.normalize(agentRoot).toLowerCase();
  const normProject = path.normalize(projectRoot).toLowerCase();
  if (normProject === normAgent || normProject.startsWith(normAgent + path.sep)) {
    const relocated = path.join(parentDir, slug);
    engineerLog(
      `[EXTERNAL-SANDBOX] ⚠ Supplied path was inside agent root — relocated to: ${relocated}`,
    );
    projectRoot = relocated;
  }

  return {
    projectRoot,
    backendRoot:    path.join(projectRoot, 'backend'),
    frontendRoot:   path.join(projectRoot, 'frontend'),
    memoryBankRoot: path.join(projectRoot, 'memory-bank'),
    envFilePath:    path.join(projectRoot, '.env'),
    projectSlug:    slug,
    isNew:          !existsSync(projectRoot),
  };
}

// ─── Directory bootstrap ──────────────────────────────────────────────────────

/** Create the sandbox root + backend/frontend sub-directories if absent. */
export function bootstrapSandboxDirs(sandbox: SandboxConfig): void {
  mkdirSync(sandbox.backendRoot,    { recursive: true });
  mkdirSync(sandbox.frontendRoot,   { recursive: true });
  mkdirSync(sandbox.memoryBankRoot, { recursive: true });
  engineerLog(`[EXTERNAL-SANDBOX] Directories bootstrapped → ${sandbox.projectRoot}`);
}

// ─── Project .env writer ──────────────────────────────────────────────────────

/**
 * Writes a localized .env into the external project root containing its own
 * ports and path configuration. Skips silently if the file already exists.
 */
export function writeProjectEnv(
  sandbox: SandboxConfig,
  overrides?: Record<string, string>,
): void {
  if (existsSync(sandbox.envFilePath)) {
    engineerLog(`[EXTERNAL-SANDBOX] .env already exists — keeping: ${sandbox.envFilePath}`);
    return;
  }

  const backendPort  = overrides?.['PORT']          ?? '3001';
  const frontendPort = overrides?.['FRONTEND_PORT'] ?? '5173';

  const lines: string[] = [
    `# Auto-generated by QA Feature Engineer`,
    `# Project: ${sandbox.projectSlug}`,
    ``,
    `PORT=${backendPort}`,
    `FRONTEND_PORT=${frontendPort}`,
    `BASE_APP_URL=http://localhost:${backendPort}`,
    `FRONTEND_APP_URL=http://localhost:${frontendPort}`,
    `ROUTES_DIR=${path.join(sandbox.backendRoot, 'src', 'routes')}`,
    `GIT_REPO_ROOT=${sandbox.backendRoot}`,
    ``,
    ...(overrides
      ? Object.entries(overrides)
          .filter(([k]) => !['PORT', 'FRONTEND_PORT'].includes(k))
          .map(([k, v]) => `${k}=${v}`)
      : []),
  ];

  mkdirSync(sandbox.projectRoot, { recursive: true });
  writeFileSync(sandbox.envFilePath, lines.join('\n') + '\n', 'utf-8');
  engineerLog(`[EXTERNAL-SANDBOX] .env written → ${sandbox.envFilePath}`);
}

// ─── CLI feedback ─────────────────────────────────────────────────────────────

/** Print the canonical "sandbox locked" banner visible in the CLI output. */
export function logSandboxLocked(sandbox: SandboxConfig): void {
  const isNewLabel = sandbox.isNew ? pc.yellow(' (NEW)') : pc.green(' (existing)');
  console.log('');
  console.log(`📂 ${pc.bold('[EXTERNAL-SANDBOX]')} Target workspace locked at: ${pc.cyan(sandbox.projectRoot)}${isNewLabel}`);
  console.log(`   ${pc.dim('Backend  →')} ${sandbox.backendRoot}`);
  console.log(`   ${pc.dim('Frontend →')} ${sandbox.frontendRoot}`);
  console.log(`   ${pc.dim('Memory   →')} ${sandbox.memoryBankRoot}`);
  console.log(`   ${pc.dim('Env      →')} ${sandbox.envFilePath}`);
  console.log('');
}

// lazy import to avoid circular dep — picocolors is used only in logSandboxLocked
import pc from 'picocolors';
